<?php

use Magento\Framework\View\Element\Template;

/** @var Template $block */
if ($block->getDecoViewModel()->isRiskifiedEnabled()): ?>
    <script>
        require([
            'jquery',
            'eligible',
            'jquery/ui',
            'domReady!'
        ], function($, eligible) {
            $(document).on('paymentFail', function (e) {
                <?php if ($block->getDecoViewModel()->isEnabled()): ?>
                    $.getScript('https://sandboxapp.decopayments.com/be/widget/widget.js?shop_url=<?php echo $block->getDecoViewModel()->getShopDomain(); ?>&session_id=<?php echo $block->getDecoViewModel()->getSessionId(); ?>', function( data, textStatus, jqxhr ) {
                        eligible.paymentFail(
                            "<?= $block->getDecoViewModel()->getButtonColor() ?>",
                            "<?= $block->getDecoViewModel()->getButtonTextColor() ?>",
                            "<?= $block->getDecoViewModel()->getLogoUrl() ?>"
                        );
                    });
                <?php endif; ?> 
            });
        });
    </script>
<?php endif; ?>
